export class DropZone {
  getDropZone() {
    return `
      <div class="drop-zone__box drop-zone__underdown-30" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-29" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-28" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-27" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-26" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-25" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-24" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-23" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-22" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-21" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-20" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-19" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-18" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-17" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-16" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-15" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-14" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-13" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-12" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-11" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-10" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-9" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-8" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-7" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-6" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-5" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-4" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-3" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-2" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underdown-1" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-50" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-49" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-48" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-47" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-46" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-45" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-44" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-43" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-42" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-41" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-40" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-39" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-38" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-37" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-36" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-35" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-34" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-33" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-32" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-31" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-30" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-29" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-28" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-27" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-26" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-25" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-24" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-23" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-22" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-21" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-20" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-19" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-18" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-17" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-16" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-15" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-14" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-13" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-12" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-11" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-10" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-9" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-8" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-7" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-6" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-5" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-4" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-3" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-2" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__underbottom-1" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-50" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-49" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-48" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-47" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-46" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-45" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-44" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-43" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-42" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-41" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-40" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-39" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-38" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-37" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-36" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-35" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-34" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-33" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-32" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-31" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-30" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-29" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-28" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-27" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-26" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-25" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-24" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-23" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-22" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-21" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-20" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-19" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-18" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-17" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-16" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-15" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-14" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-13" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-12" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-11" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-10" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-9" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-8" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-7" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-6" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-5" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-4" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-3" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-2" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__bottom-1" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-25" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-24" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-23" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-22" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-21" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-20" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-19" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-18" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-17" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-16" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-15" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-14" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-13" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-twelve" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-eleven" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-ten" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-nine" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-eight" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-seven" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-six" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-five" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-four" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-three" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-two" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__center-one" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-therteen" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-twelve" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-eleven" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-ten" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-nine" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-eight" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-seven" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-six" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-five" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-four" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-three" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-two" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__down-one" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-ten" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-nine" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-eight" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-seven" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-six" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-five" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-four" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-three" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-two" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__middle-one" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-eleven" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-ten" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-nine" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-eight" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-seven" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-six" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-five" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-four" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-three" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-two" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top-one" data-drop-target="true"></div>
                                    <div class="drop-zone__box drop-zone__top" data-drop-target="true"></div>
    `;
  }
}
